# Etapa 1: Build
FROM node:20-alpine AS builder

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos para o container
COPY package*.json ./
COPY . .

# Instala dependências e compila o app
RUN npm install
RUN npm run build

# Etapa 2: Produção
FROM node:20-alpine AS runner

WORKDIR /app

# Copia apenas o necessário da build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/next.config.ts ./

# Porta padrão do Next.js
EXPOSE 3000

# Comando de inicialização
CMD ["npm", "start"]
