services:
  db-cliente:
    image: postgres:17.4
    container_name: db-cliente
    ports:
      - '14000:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: cliente

  db-funcionario:
    image: postgres:17.4
    container_name: db-funcionario
    ports:
      - '14001:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: funcionario

  db-reserva:
    image: postgres:17.4
    container_name: db-reserva
    ports:
      - '14002:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: reserva

  db-voos:
    image: postgres:17.4
    container_name: db-voos
    ports:
      - '14003:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: voos

  db-auth:
    image: mongo:latest
    container_name: db-auth
    ports:
      - '14004:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 123mudar
      MONGO_INITDB_ROOT_PASSWORD: 123mudar
      MONGO_INITDB_DATABASE: auth

  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "14005:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 123mudar
      RABBITMQ_DEFAULT_PASS: 123mudar
  ms-auth:
    build:
      context: ./backend
      dockerfile: ms-auth/Dockerfile
    container_name: ms-auth
    ports:
      - "8084:8084"
    depends_on:
      - db-auth
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_HOST: db-auth
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: auth
      SPRING_DATA_MONGODB_USERNAME: 123mudar
      SPRING_DATA_MONGODB_PASSWORD: 123mudar
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: 123mudar
      SPRING_RABBITMQ_PASSWORD: 123mudar

      API_JWT_SECRET: H/JRasY4dHW7tWhKiUdEoQJaPJKdAl6mHh6MOIJXMknlI1x/RZBvfdPc2fAvqD4yFJgXquQASOi5BXPhcagPLA==

      INTEGRATION_CLIENT_MSCLIENTE_URL: http://ms-cliente:8080/clientes
  ms-cliente:
    build:
      context: ./backend
      dockerfile: ms-cliente/Dockerfile
    container_name: ms-cliente
    ports:
      - "8080:8080"
    depends_on:
      - db-cliente
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-cliente:5432/cliente
      SPRING_DATASOURCE_USERNAME: 123mudar
      SPRING_DATASOURCE_PASSWORD: 123mudar
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: 123mudar
      SPRING_RABBITMQ_PASSWORD: 123mudar
