services:
  db-cliente:
    image: postgres:17.4
    container_name: db-cliente
    ports:
      - '14000:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: cliente

  db-funcionario:
    image: postgres:17.4
    container_name: db-funcionario
    ports:
      - '14001:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: funcionario

  db-reserva:
    image: postgres:17.4
    container_name: db-reserva
    ports:
      - '14002:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: reserva

  db-voos:
    image: postgres:17.4
    container_name: db-voos
    ports:
      - '14003:5432'
    environment:
      POSTGRES_PASSWORD: 123mudar
      POSTGRES_USER: 123mudar
      POSTGRES_DB: voos

  db-auth:
    image: mongo:latest
    container_name: db-auth
    ports:
      - '14004:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 123mudar
      MONGO_INITDB_ROOT_PASSWORD: 123mudar
      MONGO_INITDB_DATABASE: auth

  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "14005:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 123mudar
      RABBITMQ_DEFAULT_PASS: 123mudar
  ms-auth:
    build:
      context: ./backend
      dockerfile: ms-auth/Dockerfile
    container_name: ms-auth
    ports:
      - "8084:8084"
    depends_on:
      - db-auth
      - rabbitmq
  ms-cliente:
    build:
      context: ./backend
      dockerfile: ms-cliente/Dockerfile
    container_name: ms-cliente
    ports:
      - "8080:8080"
    depends_on:
      - db-cliente
      - rabbitmq
  ms-reserva:
    build:
      context: ./backend
      dockerfile: ms-reserva/Dockerfile
    container_name: ms-reserva
    ports:
      - "8082:8082"
    depends_on:
      - db-reserva
      - rabbitmq
  ms-voos:
    build:
      context: ./backend
      dockerfile: ms-voos/Dockerfile
    container_name: ms-voos
    ports:
      - "8083:8083"
    depends_on:
      - db-voos
      - rabbitmq
